In [6]:
import numpy as np
x = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
x = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9] ], dtype=complex)
print(x)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [10]:
import numpy as np
x = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)
#traverse all elements
for i in x:  #row
 for j in i: #column
   print(j, end=" ")
print() #new line

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3 4 5 6 7 8 9 


In [15]:
y = np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
z = np.ones((3,2), dtype = np.int32)
z

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)